// <auto-generated />
using System;
using F1Pontszamitos_S6.DataB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Pontszamitos_S6.Migrations
{
    [DbContext(typeof(DriversDbContext))]
    partial class DriversDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("F1Pontszamitos_S6.Shared.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FastestLapList")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishingPositions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Team_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DriversTable");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Hamilton",
                            ShortName = "HAM",
                            Team_id = 10,
                            isActive = true
                        },
                        new
                        {
                            Id = 50,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Russel",
                            ShortName = "RUS",
                            Team_id = 10,
                            isActive = true
                        },
                        new
                        {
                            Id = 58,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Leclerc",
                            ShortName = "LEC",
                            Team_id = 1,
                            isActive = true
                        },
                        new
                        {
                            Id = 1,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Sainz",
                            ShortName = "SAI",
                            Team_id = 1,
                            isActive = false
                        },
                        new
                        {
                            Id = 9,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Verstappen",
                            ShortName = "VER",
                            Team_id = 2,
                            isActive = true
                        },
                        new
                        {
                            Id = 14,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Perez",
                            ShortName = "PER",
                            Team_id = 2,
                            isActive = false
                        },
                        new
                        {
                            Id = 62,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Albon",
                            ShortName = "ALB",
                            Team_id = 3,
                            isActive = true
                        },
                        new
                        {
                            Id = 132,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Sargeant",
                            ShortName = "SAR",
                            Team_id = 3,
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Alonso",
                            ShortName = "ALO",
                            Team_id = 4,
                            isActive = true
                        },
                        new
                        {
                            Id = 19,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Stroll",
                            ShortName = "STR",
                            Team_id = 4,
                            isActive = true
                        },
                        new
                        {
                            Id = 59,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Gasly",
                            ShortName = "GAS",
                            Team_id = 5,
                            isActive = true
                        },
                        new
                        {
                            Id = 17,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Ocon",
                            ShortName = "OCO",
                            Team_id = 5,
                            isActive = true
                        },
                        new
                        {
                            Id = 94,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Tsunoda",
                            ShortName = "TSU",
                            Team_id = 6,
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Ricciardo",
                            ShortName = "RIC",
                            Team_id = 6,
                            isActive = true
                        },
                        new
                        {
                            Id = 10,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Hulkenberg",
                            ShortName = "HUL",
                            Team_id = 7,
                            isActive = true
                        },
                        new
                        {
                            Id = 11,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Magnussen",
                            ShortName = "MAG",
                            Team_id = 7,
                            isActive = true
                        },
                        new
                        {
                            Id = 54,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Norris",
                            ShortName = "NOR",
                            Team_id = 8,
                            isActive = true
                        },
                        new
                        {
                            Id = 112,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Piastri",
                            ShortName = "PIA",
                            Team_id = 8,
                            isActive = true
                        },
                        new
                        {
                            Id = 80,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Zhou",
                            ShortName = "ZHO",
                            Team_id = 9,
                            isActive = true
                        },
                        new
                        {
                            Id = 15,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Bottas",
                            ShortName = "BOT",
                            Team_id = 9,
                            isActive = true
                        },
                        new
                        {
                            Id = 120,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Szarka",
                            ShortName = "SZA",
                            Team_id = 2,
                            isActive = true
                        },
                        new
                        {
                            Id = 121,
                            FastestLapList = "[]",
                            FinishingPositions = "[]",
                            Name = "Bagosi",
                            ShortName = "BAG",
                            Team_id = 1,
                            isActive = true
                        });
                });

            modelBuilder.Entity("F1Pontszamitos_S6.Shared.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RacesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bahrain GP",
                            ShortName = "BHR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Las Vegas GP",
                            ShortName = "VEGAS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Miami GP",
                            ShortName = "MIAMI"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brazilian GP",
                            ShortName = "BRAZ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Hungarian GP",
                            ShortName = "HUN"
                        });
                });

            modelBuilder.Entity("F1Pontszamitos_S6.Shared.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver_ids")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamsTable");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            BgColor = "#0da49f",
                            Driver_ids = "[7,50]",
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 1,
                            BgColor = "#fe0d0d",
                            Driver_ids = "[58,1,121]",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 2,
                            BgColor = "#021652",
                            Driver_ids = "[9,14,120]",
                            Name = "Red Bull"
                        },
                        new
                        {
                            Id = 3,
                            BgColor = "#0b3b7a",
                            Driver_ids = "[62,132]",
                            Name = "Williams"
                        },
                        new
                        {
                            Id = 4,
                            BgColor = "#00533a",
                            Driver_ids = "[3,19]",
                            Name = "Aston"
                        },
                        new
                        {
                            Id = 5,
                            BgColor = "#04111f",
                            Driver_ids = "[59,17]",
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 6,
                            BgColor = "#1534cc",
                            Driver_ids = "[94,2]",
                            Name = "Visa CashApp RB"
                        },
                        new
                        {
                            Id = 7,
                            BgColor = "#ffffff",
                            Driver_ids = "[10,11]",
                            Name = "Haas"
                        },
                        new
                        {
                            Id = 8,
                            BgColor = "#ff6c0b",
                            Driver_ids = "[54,112]",
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 9,
                            BgColor = "#000000",
                            Driver_ids = "[80,15]",
                            Name = "Stake Sauber"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
