// <auto-generated />
using F1Pontszamitos_S6.DataB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Pontszamitos_S6.Migrations
{
    [DbContext(typeof(DriversDbContext))]
    partial class DriversDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("F1Pontszamitos_S6.Shared.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FastestLapCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinishingPositions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DriversTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FastestLapCount = 5,
                            FinishingPositions = "[3,4,1,20]",
                            Name = "Verstappen",
                            Point = 277,
                            ShortName = "VER",
                            Team = "Red Bull"
                        },
                        new
                        {
                            Id = 2,
                            FastestLapCount = 2,
                            FinishingPositions = "[1,2,3,4]",
                            Name = "Norris",
                            Point = 199,
                            ShortName = "NOR",
                            Team = "McLaren"
                        },
                        new
                        {
                            Id = 3,
                            FastestLapCount = 0,
                            FinishingPositions = "[5,1,1,2]",
                            Name = "Leclerc",
                            Point = 177,
                            ShortName = "LEC",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 4,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Piastri",
                            Point = 167,
                            ShortName = "PIA",
                            Team = "McLaren"
                        },
                        new
                        {
                            Id = 5,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Sainz",
                            Point = 162,
                            ShortName = "SAI",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 6,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Hamilton",
                            Point = 150,
                            ShortName = "HAM",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 7,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Perez",
                            Point = 131,
                            ShortName = "PER",
                            Team = "Red Bull"
                        },
                        new
                        {
                            Id = 8,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Russel",
                            Point = 116,
                            ShortName = "RUS",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 9,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Alonso",
                            Point = 49,
                            ShortName = "ALO",
                            Team = "Aston"
                        },
                        new
                        {
                            Id = 10,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Stroll",
                            Point = 24,
                            ShortName = "STR",
                            Team = "Aston"
                        },
                        new
                        {
                            Id = 11,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Hulkenberg",
                            Point = 22,
                            ShortName = "HUL",
                            Team = "Haas"
                        },
                        new
                        {
                            Id = 12,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Tsunoda",
                            Point = 22,
                            ShortName = "TSU",
                            Team = "Tauri"
                        },
                        new
                        {
                            Id = 13,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Ricciardo",
                            Point = 11,
                            ShortName = "RIC",
                            Team = "Tauri"
                        },
                        new
                        {
                            Id = 14,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Gasly",
                            Point = 6,
                            ShortName = "GAS",
                            Team = "Alpine"
                        },
                        new
                        {
                            Id = 15,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Magnussen",
                            Point = 5,
                            ShortName = "MAG",
                            Team = "Haas"
                        },
                        new
                        {
                            Id = 16,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Albon",
                            Point = 4,
                            ShortName = "ALB",
                            Team = "Williams"
                        },
                        new
                        {
                            Id = 17,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Ocon",
                            Point = 4,
                            ShortName = "OCO",
                            Team = "Alpine"
                        },
                        new
                        {
                            Id = 18,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Zhou",
                            Point = 0,
                            ShortName = "ZHO",
                            Team = "Alfa"
                        },
                        new
                        {
                            Id = 19,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Sargeant",
                            Point = 0,
                            ShortName = "SAR",
                            Team = "Williams"
                        },
                        new
                        {
                            Id = 20,
                            FastestLapCount = 0,
                            FinishingPositions = "[16,13,20,19]",
                            Name = "Bottas",
                            Point = 0,
                            ShortName = "BOT",
                            Team = "Alfa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
